#!/bin/bash
LOCATIONS=(
"/usr/lib/python3.6/site-packages/gufw/gufw.py"
"/usr/lib/python3.6/dist-packages/gufw/gufw.py"
"/usr/share/gufw/gufw/gufw.py"
)

for ((i = 0; i < ${#LOCATIONS[@]}; i++))
do
    if [[ -e "${LOCATIONS[${i}]}" ]]; then
        python3 ${LOCATIONS[${i}]} $1
    fi
done


