#!/bin/sh

# Simple wrapper to tell pkgconf to behave as a platform-specific version of pkg-config
# Platform: x86_64-pc-linux-gnu

: ${PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/usr/share/pkgconfig}
: ${PKG_CONFIG_SYSTEM_LIBRARY_PATH=/usr/lib} 
: ${PKG_CONFIG_SYSTEM_INCLUDE_PATH=/usr/include}
export PKG_CONFIG_LIBDIR PKG_CONFIG_SYSTEM_LIBRARY_PATH PKG_CONFIG_SYSTEM_INCLUDE_PATH

exec pkgconf "$@"
